# ===============================
# = Server Cofiguration
# ===============================
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

# ===============================
# = DATA SOURCE
# ===============================
spring:
  eureka:
    client:
      service-url:
        default-zone: http://localhost:8081/eureka
  #  datasource:
#    username:
#    password:
#
#    url: jdbc:mysql://localhost:3306/bugs_final?autoReconnect=true&useSSL=false
#    testWhileIdle: true
#    initialization-mode: always
#
#    validationQuery: SELECT 1
#
## ===============================
## = JPA / HIBERNATE
## ===============================
#  jpa:
#    show_sql: true
#    format_sql: true
#    hibernate:
#      ddl-auto: update
#
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        enable_lazy_load_no_trans: true

# ===============================
# =Provide Application Name
# ===============================
  application:
    name: Digi-dairy-API

# ===============================
# = H2 CONFIG
# ===============================
  h2:
    console:
      enabled: true
      path: /h2

